name: Build

on:
  push:
  schedule:
    - cron: '0 8 * * *'

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.8.4', '8.10.7', '9.0.1']
        cabal: ['3.4']
        os:
        - 'ubuntu-18.04'
        - 'ubuntu-20.04'
        - 'macOS-latest'
        # - 'windows-latest' # windows builds generally work but are flaky on the github runners
        flags: ['', '-ftest-cryptonite -fbenchmark-cryptonite -fwith-openssl']

    steps:

    # Setup
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install GHC and Cabal
      uses: haskell/actions/setup@v1.2
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}

    # Restore Packages from Caches
    - uses: actions/cache@v2
      name: Cache dist-newstyle
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ matrix.os }}-${{ matrix.ghc }}-0-cabal

    # Build
    - name: Update package database
      run: cabal update
    - name: Configure build
      run: |
        cabal build all --dry-run ${{ matrix.flags }}
        cabal freeze
    - name: Install build dependencies
      run: cabal build --only-dependencies ${{ matrix.flags }}
    - name: Build library
      run: cabal build ${{ matrix.flags }}

    # Tests
    - name: Run Tests
      run: cabal test test:tests ${{ matrix.flags }}

    # Benchmarks
    - name: Run Benchmarks
      run: cabal bench bench:benchmarks ${{ matrix.flags }}

