name: Build

on:
  push:

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.7', '9.0.1', '9.2']
        cabal: ['3.6']
        os: ['ubuntu-20.04', 'ubuntu-22.04']
        cryptonite: ['-test-cryptonite -benchmark-cryptonite', '+test-cryptonite +benchmark-cryptonite']
        openssl: [ '+with-openssl', '-with-openssl' ]
        include:
        - include:
          ghc: '9.0.1'
          cabal: '3.6'
          os: 'macOS-latest'
          cryptonite: '+test-cryptonite +benchmark-cryptonite'
          openssl: '+with-openssl'
        - include:
          ghc: '8.10.7'
          cabal: '3.6'
          os: 'macOS-latest'
          cryptonite: '+test-cryptonite +benchmark-cryptonite'
          openssl: '+with-openssl'

    steps:

    # Setup
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install GHC and Cabal
      uses: haskell/actions/setup@v2
      with:
         ghc-version: ${{ matrix.ghc }}
         cabal-version: ${{ matrix.cabal }}

    # Restore Packages from Caches
    - uses: pat-s/always-upload-cache@v2.1.5
      name: Cache dist-newstyle
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ matrix.os }}-${{ matrix.ghc }}-0-cabal

    - name: Check OpenSSL Version
      run: |
        which openssl
        openssl version

    # Local cabal config
    - name: Create local cabal config
      if: "matrix.ghc != '9.2'"
      run: |
        cat > cabal.project.local <<EOF
        package hashes
          documentation: True
          benchmarks: True
          tests: True
          flags: ${{ matrix.openssl }} ${{ matrix.cryptonite }}
        EOF
    - name: Create local cabal config
      if: "matrix.ghc == '9.2'"
      run: |
        cat > cabal.project.local <<EOF
        package hashes
          documentation: True
          benchmarks: False
          tests: False
          flags: ${{ matrix.openssl }} ${{ matrix.cryptonite }}
        allow-newer: base
        allow-newer: template-haskell
        allow-newer: ghc-prim
        allow-newer: ghc-bignum
        EOF

    # Build
    - name: Update package database
      run: cabal update
    - name: Configure build
      run: |
        cabal build all --dry-run
        cabal freeze
    - name: Install build dependencies
      run: cabal build --only-dependencies
    - name: Build library
      run: cabal build

    # Tests
    - name: Run Tests
      if: "matrix.ghc != '9.2'"
      run: cabal test test:tests

    # Benchmarks
    - name: Run Benchmarks
      if: "matrix.ghc != '9.2'"
      run: cabal bench bench:benchmarks

